name: Maven Unit Tests

on:
    push:
        branches: [ master, develop*, release* ]
    pull_request:
        branches: [ master, develop*, release* ]
    workflow_dispatch:

jobs:
    maven-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: ['8']

        name: Run Maven Tests on JDK ${{ matrix.java }}

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    cache: 'maven'
                    java-version: ${{ matrix.java }}

            -   name: Run Maven Tests (JDK ${{ matrix.Java }})
                run: mvn clean test

    ui-unit-tests:
        runs-on: ubuntu-latest

        env:
            node-version: 20.x

        name: Run UI Unit Tests

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Node ${{ matrix.node }}
                uses: actions/setup-node@v4
                with:
                    cache: 'npm'
                    cache-dependency-path: '**/package-lock.json'
                    node-version: ${{ env.node-version }}

            -   name: Install NPM Dependencies
                run: npm ci
                working-directory: ui.apps

            -   name: Run UI Unit Tests (Node ${{ matrix.node }})
                run: npm run test
                working-directory: ui.apps
