name: Maven Unit Tests

on:
    push:
        branches: [ master, develop*, release* ]
    pull_request:
        branches: [ master, develop*, release* ]
    workflow_dispatch:

jobs:
    maven-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: ['8']

        name: Run Maven Tests on JDK ${{ matrix.java }}

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: ${{ matrix.java }}
                    cache: 'maven'

            -   name: Run Maven Tests (JDK ${{ matrix.Java }})
                run: mvn clean test
